#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1661525085
ios_app_country                           : de                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : #/presskit.zip                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : ImmoAssistant
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Immobilienkennzahlen schnell und einfach berechnen.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Gustav Gutsche
your_link                                 : 
your_city                                 : Mainz
email_address                             : Gustav_Gutsche@icloud.com
facebook_username                         :                                          
instagram_username                        : 
twitter_username                          : 
github_username                           : Gustav-Gutsche
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Immo Assistant
    description                           : Mit Immo Assistant stehen Ihnen schnelle Berechnungen für mehr als 50 essenzielle Immobilien-Kennzahlen zur Verfügung.
    fontawesome_icon_name                 : house
    
  - title                                 : Updates
    description                           : Immo Assistant entwickelt sich ständig weiter, um Ihnen regelmäßig innovative und nützliche neue Funktionen für Ihre Immobilienberechnungen zu bieten.
    fontawesome_icon_name                 : star
    
  - title                                 : Tilgungsrechner
    description                           : Zusätzlich bietet Immo Assistant einen praktischen Tilgungsrechner, um Ihre Finanzierungspläne effizient zu gestalten.
    fontawesome_icon_name                 : chart-line

  - title                                 : iPhone, iPad und Mac
    description                           : Immo Assistant ist für alle Ihre Geräte verfügbar.
    fontawesome_icon_name                 : desktop

  - title                                 : Quick Calculation
    description                           : Immo Assistant verfügt über einen Quick Calculation Modus, der es ermöglicht, die wichtigsten Kennzahlen für Immobilien schnell und effizient zu berechnen.
    fontawesome_icon_name                 : forward-fast
    
  - title                                 : Feedback
    description                           : Immo Assistant bietet eine direkte Feedback-Option, durch die Nutzer aktiv neue Funktionen vorschlagen und so die App-Gestaltung mitgestalten können.
    fontawesome_icon_name                 : message
  
  - title                                 : Datenschutz
    description                           : Immo Assistant schützt Ihre Privatsphäre – keine Datensammlung von Nutzern.
    fontawesome_icon_name                 : lock

  - title                                 : Keine Werbung
    description                           : Immo Assistant bietet ein werbefreies Nutzererlebnis für ungestörte Immobilienberechnungen.
    fontawesome_icon_name                 : ban

  - title                                 : Keine Abonnements und In-App-Käufe
    description                           : Immo Assistant bietet vollständigen Funktionsumfang ohne Abonnements und In-App-Käufe – ein echter Mehrwert für Ihre Immobilienberechnungen.
    fontawesome_icon_name                 : hand-holding-dollar

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0
topbar_title_color                        : "#000"

cover_image                               : #assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#000000"
cover_overlay_transparency                : 0

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#000"

link_color                                : "#FF453A"

app_title_color                           : "#fff"
app_price_color                           : "#fff"
app_description_color                     : "#fff"

feature_title_color                       : "#fff"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#FF453A"
feature_icons_background_color            : "#222"

social_icons_foreground_color             : "#FF453A"
social_icons_background_color             : "#222"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
